name: Shell Commands

on:
  push:
    branches:
     - main

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
       - name: Multiline script
        run: |
          node -v
          npm -v
